version: '3.8'

services:
  ingesta-cartelera:
    build: .
    container_name: ingesta_cartelera_c
    env_file: .env
    volumes:
      - ./salidas:/app  # para que puedas ver el archivo CSV localmente (opcional)
    networks:
      - red_ingesta
    restart: unless-stopped

networks:
  red_ingesta:
    driver: bridge
